name: CI-CD-Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t pranam2835/db-project:latest ./app

    - name: Push Docker image
      run: |
        docker login -u pranam2835 -p ${{ secrets.DOCKER_PASSWORD }}
        docker push pranam2835/db-project:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/
